version: "3"
services:
  book-catalog:
    build:
      context: book_catalog
      dockerfile: Dockerfile
    image: book-catalog
    container_name: book-catalog
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
  inventory:
    build:
      context: inventory_management
      dockerfile: Dockerfile
    image: inventory-management
    container_name: inventory_management
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=${DATABASE_URL}