apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: book-catalog
          image: sit722shadrack.azurecr.io/book-catalog:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://sit722_a2b2_user:OgIuQqBMdlRFMqK3N4y0riw5umzFKRXq@dpg-crtsl4e8ii6s73alm9o0-a.oregon-postgres.render.com/sit722_a2b2
        - name: inventory-management
          image: sit722shadrack.azurecr.io/inventory-management:latest
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: postgresql://sit722_a2b2_user:OgIuQqBMdlRFMqK3N4y0riw5umzFKRXq@dpg-crtsl4e8ii6s73alm9o0-a.oregon-postgres.render.com/sit722_a2b2
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: microservice
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: microservice
  ports:
    - port: 8001
      targetPort: 8001
  type: LoadBalancer